// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package logger

import "github.com/Mrzrb/goerr/core"

func NewLoggerProcess(FileExporter core.FileExporter) LoggerProcess {
	returnValue := LoggerProcess{
		FileExporter: FileExporter,
	}

	return returnValue
}
