// Code generated by aop annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		aop: 0.1

package sub

import (
	"github.com/Mrzrb/goerr/annotations/aop_core"
	"github.com/Mrzrb/goerr/examples/aop/common"
)

type BisClientProxy struct {
	inner *BisClient

	aspect0 *common.Common
}

func NewBisClientProxy(inner *BisClient) *BisClientProxy {
	return &BisClientProxy{
		inner: inner,

		aspect0: &common.Common{},
	}
}

type BisClientInterface interface {
	Hello() (ret1 int64, ret2 error)
}

func (r *BisClientProxy) Hello() (ret1 int64, ret2 error) {
	joint := aop_core.Jointcut{
		TargetName: "BisClient",
		TargetType: "BisClient",
		MethodName: "Hello",
		Args:       []aop_core.Args{},
		MeteInfo:   "{\"structMeta\":{\"mete\":{\"Aop\":{\"Target\":\"Common\",\"Type\":\"point\"}}},\"procedureMeta\":{\"Hello\":{\"mete\":{\"Aop\":{\"Target\":\"\",\"Type\":\"pointcut\"}}}}}",
	}

	runContext := aop_core.RunContext{}
	returnResult := aop_core.ReturnResult{}

	returnResult.Args = append(returnResult.Args, &aop_core.Args{Name: "", Type: "int64", Value: ret1})
	returnResult.Args = append(returnResult.Args, &aop_core.Args{Name: "", Type: "error", Value: ret2})

	mutableArgs := aop_core.MuteableArgs{}

	runContext.MuteableArgs = mutableArgs
	runContext.ReturnResult = returnResult

	joint.Fn = func() error {
		ret1, ret2 = r.inner.Hello()

		if ret2 != nil {
			return ret2
		}

		runContext.ReturnResult.Args[0].Value = ret1
		runContext.ReturnResult.Args[1].Value = ret2
		return nil
	}

	aop_core.GenerateChain(&joint, &runContext,

		func(j aop_core.Jointcut, m *aop_core.RunContext) error {
			return r.aspect0.Handler(j, m)
		},
	)
	joint.Fn()
	return aop_core.Cast[int64](returnResult.Args[0].Value), aop_core.Cast[error](returnResult.Args[1].Value)
}
