// Code generated by GetterSetter annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		GetterSetter: 0.1

package main

import (
	"github.com/Mrzrb/goerr/annotations/getset"
)

func (c *Ts) GetField1() string {
	return c.Field1
}

func (c *Ts) GetField2() getset.Getter {
	return c.Field2
}

func (c *Ts) GetTest() any {
	return c.Test
}

func (c *Ts) GetInfo() innerStruct {
	return c.Info
}

func (c *Ts) GetInfos() *innerStruct {
	return c.Infos
}
