// Code generated by Constructor annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		Constructor: 1.0.0

package core

var Assembler = NewAssembler()

func NewAssembler() assembler {
	returnValue := assembler{}

	return returnValue
}

func NewExporter(Assembler *assembler) exporter {
	returnValue := exporter{
		Assembler: Assembler,
		Files:     []Outputer{},
		cache:     make(map[string]any),
	}

	return returnValue
}
