// Code generated by autowire annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		autowire: 0.1

package main

import (
	"github.com/Mrzrb/goerr/di"
	"github.com/Mrzrb/goerr/examples/autowire/sub"
	"github.com/samber/do/v2"
)

func init() {

	app := App{}

	do.ProvideNamedValue(di.GlobalInjector, "main.App", app)
	do.Provide(di.GlobalInjector, func(i do.Injector) (App, error) {
		return app, nil
	})

	main_newname := NewName()
	do.ProvideNamedValue(di.GlobalInjector, "main.Name", main_newname)
	do.Provide(di.GlobalInjector, func(i do.Injector) (*Name, error) {
		return main_newname, nil
	})

	sub_newsub := sub.NewSub()
	do.ProvideNamedValue(di.GlobalInjector, "sub.Sub", sub_newsub)
	do.Provide(di.GlobalInjector, func(i do.Injector) (*sub.Sub, error) {
		return sub_newsub, nil
	})

}
