// Code generated by autowire annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		autowire: 0.1

package main

import (
	"github.com/Mrzrb/goerr/di"
	"github.com/samber/do/v2"
)

func init() {

	main_newname := NewName()
	do.ProvideNamedValue(di.GlobalInjector, "main.Name", main_newname)
	do.Provide(di.GlobalInjector, func(i do.Injector) (*Name, error) {
		return main_newname, nil
	})

	name1 := Name1{}

	do.ProvideNamedValue(di.GlobalInjector, "main.Name1", name1)
	do.Provide(di.GlobalInjector, func(i do.Injector) (Name1, error) {
		return name1, nil
	})

	app := App{
		Name:  *main_newname,
		Name1: &name1,
	}

	do.ProvideNamedValue(di.GlobalInjector, "main.App", app)
	do.Provide(di.GlobalInjector, func(i do.Injector) (App, error) {
		return app, nil
	})

}
