// Code generated by aop annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		aop: 0.1

package twoaspect

import (
	"github.com/Mrzrb/goerr/annotations/aop"
	"github.com/Mrzrb/goerr/tests/testsdata"
	"twoaspect"
)

type ServiceProxy struct {
	inner *Service

	aspect0 *testsdata.BaseAspect
	aspect1 *BaseAspect
}

func NewServiceProxy(inner *Service) *ServiceProxy {
	return &ServiceProxy{
		inner: inner,

		aspect0: &testsdata.BaseAspect{},
		aspect1: &BaseAspect{},
	}
}

type ServiceInterface interface {
	Hello() (ret1 error)

	Hello() (ret1 error)

	Hello() (ret1 error)

	Hello1() (ret1 error)
}

func (r *ServiceProxy) Hello() (ret1 error) {
	joint := aop.Jointcut{
		TargetName: "Service",
		TargetType: "Service",
		MethodName: "Hello",
		Args:       []aop.Args{},
		Fn: func() {
			ret1 = r.inner.Hello()
		},
	}

	fn := aop.GenerateChain(joint,

		func(j aop.Jointcut) {
			r.aspect0.Handle(j)
		},

		func(j aop.Jointcut) {
			r.aspect1.Handle(j)
		},
	)
	fn()
	return ret1
}
func (r *ServiceProxy) Hello() (ret1 error) {
	joint := aop.Jointcut{
		TargetName: "Service",
		TargetType: "Service",
		MethodName: "Hello",
		Args:       []aop.Args{},
		Fn: func() {
			ret1 = r.inner.Hello()
		},
	}

	fn := aop.GenerateChain(joint,

		func(j aop.Jointcut) {
			r.aspect0.Handle(j)
		},

		func(j aop.Jointcut) {
			r.aspect1.Handle(j)
		},
	)
	fn()
	return ret1
}
func (r *ServiceProxy) Hello() (ret1 error) {
	joint := aop.Jointcut{
		TargetName: "Service",
		TargetType: "Service",
		MethodName: "Hello",
		Args:       []aop.Args{},
		Fn: func() {
			ret1 = r.inner.Hello()
		},
	}

	fn := aop.GenerateChain(joint,

		func(j aop.Jointcut) {
			r.aspect0.Handle(j)
		},

		func(j aop.Jointcut) {
			r.aspect1.Handle(j)
		},
	)
	fn()
	return ret1
}
func (r *ServiceProxy) Hello1() (ret1 error) {
	joint := aop.Jointcut{
		TargetName: "Service",
		TargetType: "Service",
		MethodName: "Hello1",
		Args:       []aop.Args{},
		Fn: func() {
			ret1 = r.inner.Hello1()
		},
	}

	fn := aop.GenerateChain(joint,

		func(j aop.Jointcut) {
			r.aspect0.Handle(j)
		},

		func(j aop.Jointcut) {
			r.aspect1.Handle(j)
		},
	)
	fn()
	return ret1
}

type Service1Proxy struct {
	inner *Service1

	aspect0 *BaseAspect1
}

func NewService1Proxy(inner *Service1) *Service1Proxy {
	return &Service1Proxy{
		inner: inner,

		aspect0: &BaseAspect1{},
	}
}

type Service1Interface interface {
}
